#!/usr/bin/env bash
set -e # halt script on error

python script/make_pages.py

if [ "$JEKYLL_ENV" = "production"]; then
  bundle exec jekyll build --config _config.yml
  echo "production"
else
  bundle exec jekyll build --config _config_dev.yml
  echo "development"
fi

node js/create-index.js

if [[ "${TRAVIS_CI}" ]]; then
  bundle exec htmlproofer ./_site
fi
