#!/usr/bin/env bash
#!/usr/bin/env python2.7
set -e # halt script on error

python script/make_pages.py

if [ "$JEKYLL_ENV" = "production" ]; then
  bundle exec jekyll build --config _config.yml,_config_prod.yml
else
  bundle exec jekyll build --config _config.yml
fi

node js/create-index.js

if [[ "${TRAVIS_CI}" ]]; then
  bundle exec htmlproofer ./_site
fi
