#!/usr/bin/env bash
set -e # halt script on error

python script/make_pages.py

JEKYLL_ENV=production bundle exec jekyll build

node js/create-index.js

if [[ "${TRAVIS_CI}" ]]; then
  bundle exec htmlproofer ./_site
fi
